repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: pixi run mdlint --fix
        language: node
        types: [markdown]
        require_serial: true
        verbose: true
