[project]
name = "med-imagenet"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]

[dependencies]

[environments]
docs = { features = ["docs"] }
pandas = ['pandas']
dev = { features = ["dev", "docs", "lint"] }
nbia = { features = ["dev", "nbia"], no-default-feature = true }

################################################################################
# dev
################################################################################

[feature.dev.dependencies]
ipython = "*"
jupyter = "*"
rich = ">=13.9.4,<14"
click = ">=8.1.7,<9"
python-dotenv = ">=1.0.1,<2"

################################################################################
# nbia
################################################################################
[feature.nbia.dependencies]
python = ">=3.10,<3.13"

[feature.nbia.pypi-dependencies]
nbiatoolkit = ">=1.3.1, <2"


################################################################################
# docs
################################################################################

[feature.docs.dependencies]
mkdocs = "*"
mkdocs-material = ">=9.5.24,<9.6"
mkdocs-macros-plugin = ">=1.0.5,<1.1"
mkdocs-glightbox = ">=0.4.0,<0.5"
mkdocs-autorefs = ">=1.2.0,<2"
mkdocs-git-authors-plugin = ">=0.9.0,<0.10"
mike = ">=2.1.2,<2.2"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"
mkdocs-include-markdown-plugin = ">=7.0.0,<8"
mkdocs-redirects = ">=1.2.1,<2"

[feature.docs.pypi-dependencies]
mkdocs-awesome-pages-plugin = ">=2.9.1,<3"

[feature.docs.tasks]
build.description = "Build the documentation using MkDocs"
build.cmd = "mkdocs build -f mkdocs.yml"
build.inputs = ["docs", "mkdocs.yml"]
build.outputs = ["site"]

serve.description = "Serve the documentation to http://localhost:8000/"
serve.cmd = "mkdocs serve -f mkdocs.yml"

################################################################################
# lint
################################################################################

[feature.lint.dependencies]
ruff = "*"
pre-commit = ">=3.7.1,<4"
pre-commit-hooks = ">=4.6.0,<5"
markdownlint-cli = ">=0.42.0,<0.43"

[feature.lint.tasks]
pre-commit-install.description = "Install pre-commit hooks"
pre-commit-install.cmd = "pre-commit install --install-hooks -t=pre-commit -t=pre-push"
pre-commit-install.inputs = [".pre-commit-config.yaml"]

mdlint.description = "Run markdownlint"
mdlint.cmd = "markdownlint -c .markdownlint.json docs/*"
mdlint.inputs = ["docs/*", ".markdownlint.json", ".markdownlintignore"]
mdlint.depends-on = ["pre-commit-install"]

lint.description = "Run pre-commit hooks"
lint.cmd = "pre-commit run --all-files --hook-stage=manual"
lint.depends-on = ["pre-commit-install"]

[feature.pandas.dependencies]
seaborn = "*"
pandas = "*"
python = "*"
ipython = "*"
jupyter = "*"
rich = ">=13.9.4,<14"
plotly = ">=6.0.1,<7"
upsetplot = ">=0.9.0,<0.10"
