[project]
name = "med-imagenet"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
