import click
from pathlib import Path
import pandas as pd
import sys
from datetime import datetime

from imgnet.imgnet import ImgNet
from imgnet.collections.store import IndexedDatasets
from imgnet.loggers import logger
from imgnet.query import ValidQuery

@click.command(
    epilog="""
Examples:

  Download imaging data from a query manifest:

    imgnet download manifest.csv

  Download and convert DICOM files to NIfTI format:

    imgnet download manifest.csv --process

  Download data to a specific directory:

    imgnet download manifest.csv --output-dir ./my_dataset

  Pipe a manifest from another command:

    imgnet query ... | imgnet download
"""
)
@click.help_option("--help", "-h")
@click.argument(
    "manifest",
    type=click.Path(
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        resolve_path=True,
    ),
    metavar="MANIFEST",
)
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(
        exists=False,
        file_okay=False,
        dir_okay=True,
        readable=True,
        resolve_path=True,
    ),
    default=None,
    help=(
        "Directory where downloaded data will be stored. "
        "If not provided, a timestamped directory will be created "
        "in the current working directory."
    ),
)
@click.option(
    "--process",
    "-p",
    is_flag=True,
    help=(
        "Convert downloaded DICOM files to NIfTI format using "
        "med-imagetools."
    ),
)
@click.option(
    "--delete-srcdata",
    is_flag=True,
    help=(
        "Delete downloaded DICOM source files after successful processing. "
        "This frees disk space but cannot be undone."
    ),
)
@click.pass_context
def download(
    ctx: click.Context,
    manifest: str,
    output_dir: Path | None,
    process: bool,
    delete_srcdata: bool,
) -> None:
    """Download medical imaging data from an ImgNet query manifest.

    The manifest should be generated using `imgnet query` and contains
    a list of imaging series to download from indexed datasets.

    By default, downloaded files are stored in the `srcdata` directory
    inside the output directory. Use `--process` to convert downloaded
    DICOM files into NIfTI format using med-imagetools. Processed files
    are stored in the `procdata` directory.

    MANIFEST:
        Path to a CSV manifest generated by `imgnet query`.
    """
    if manifest_or_token is None and not sys.stdin.isatty():
        manifest_or_token = sys.stdin.read().strip()

    if not manifest_or_token:
        click.echo(ctx.get_help())
        ctx.exit(0)
        return

    store = IndexedDatasets()
    path = Path(manifest_or_token)
    if path.is_file():
        with path.open("r") as f:
            manifest = pd.read_csv(f)
        logger.info(f"Downloading from manifest file: {path}")
    else:
        # valid_query = ValidQuery.from_token(manifest_or_token)
        # manifest = valid_query.process(store)
        # logger.info(f"Downloading from query token: {manifest_or_token}")
        logger.warning("Downloading from query token is not implemented yet.")
        ctx.exit(1)
        return

    if output_dir is not None:
        output_dir = Path(output_dir)
    else:
        output_dir = Path.cwd() / f"imgnet_output_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        logger.warning("No output path provided, using: %s", output_dir)

    srcdata_path = output_dir / "srcdata"
    srcdata_path.mkdir(exist_ok=True, parents=True)

    imgnet = ImgNet(srcdata_path, store=store)
    imgnet.download(manifest)

    if process:
        from imgtools.autopipeline import Autopipeline
        from imgnet.collections.source import FileType
        import shutil
        procdata_path = output_dir / "procdata"
        procdata_path.mkdir(exist_ok=True, parents=True)

        for collection in manifest["Collection"].unique():
            if store.file_type(collection) == FileType.DICOM:
                logger.info(f"Processing DICOM files in collection using imgtools: {collection}")
                pipeline = Autopipeline(
                    input_directory=srcdata_path / collection,
                    output_directory=procdata_path / collection,
                )
                pipeline.run()

                if delete_srcdata:
                    logger.warning(f"Flag --delete-srcdata set. Deleting source data for collection: {collection}")
                    if (srcdata_path / collection).exists():
                        shutil.rmtree(srcdata_path / collection)
                    if (srcdata_path / ".imgtools").exists():
                        shutil.rmtree(srcdata_path / ".imgtools")
            