SUPPORTED_COLLECTIONS = [
"CTpred-Sunitinib-panNET",
"TCGA-LUSC",
"TCGA-STAD",
"LungCT-Diagnosis",
"MIDRC-RICORD-1B",
"MIDI-B-Curated-Validation",
"RIDER PHANTOM PET-CT",
"Pelvic-Reference-Data",
"Lung-Fused-CT-Pathology",
"MIDRC-RICORD-1C",
"CMB-MML",
"CMB-PCA",
"Duke-Breast-Cancer-MRI",
"TCGA-LIHC",
"Adrenal-ACC-Ki67-Seg",
"NaF PROSTATE",
"GBM-DSC-MRI-DRO",
"PDMR-833975-119-R",
"QIN LUNG CT",
"CMB-LCA",
"Spine-Mets-CT-SEG",
"CPTAC-PDA",
"QIN-BREAST-02",
"ACRIN-Contralateral-Breast-MR",
"TCGA-KIRP",
"Lung Phantom",
"QIN PET Phantom",
"TCGA-KIRC",
"HCC-TACE-Seg",
"RIDER Breast MRI",
"QIN Breast DCE-MRI",
"VICTRE",
"NSCLC-Radiomics",
"TCGA-LUAD",
"Colorectal-Liver-Metastases",
"LIDC-IDRI",
"NSCLC Radiogenomics",
"TCGA-UCEC",
"PROSTATEx",
"TCGA-BRCA",
"Prostate-MRI-US-Biopsy",
"CMB-CRC",
"Mediastinal-Lymph-Node-SEG",
"CC-Radiomics-Phantom",
"UPENN-GBM",
"CT-vs-PET-Ventilation-Imaging",
"Breast-MRI-NACT-Pilot",
"RIDER Lung PET-CT",
"TCGA-READ",
"RIDER Lung CT",
"B-mode-and-CEUS-Liver",
"Anti-PD-1_Lung",
"Lung-PET-CT-Dx",
"RIDER PHANTOM MRI",
"PDMR-Texture-Analysis",
"Prostate-Anatomical-Edge-Cases",
"ACRIN-NSCLC-FDG-PET",
"SPIE-AAPM Lung CT Challenge",
"ACRIN-FLT-Breast",
"CT4Harmonization-Multicentric",
"TCGA-PRAD",
"Soft-tissue-Sarcoma",
"TCGA-ESCA",
"CT-Phantom4Radiomics",
"ISPY2",
"4D-Lung",
"PROSTATE-MRI",
"PROSTATE-DIAGNOSIS",
"CC-Radiomics-Phantom-2",
"TCGA-KICH",
"Mouse-Mammary",
"COVID-19-AR",
"TCGA-OV",
"CPTAC-LUAD",
"CMB-AML",
"Pancreatic-CT-CBCT-SEG",
"CBIS-DDSM",
"C4KC-KiTS",
"QIN-PROSTATE-Repeatability",
"CMB-BRCA",
"MIDRC-RICORD-1A",
"PDMR-425362-245-T",
"NSCLC-Radiomics-Genomics",
"QIN-BREAST",
"PDMR-BL0293-F563",
"COVID-19-NY-SBU",
"CC-Radiomics-Phantom-3",
"RIDER Pilot",
"StageII-Colorectal-CT",
"MIDI-B-Synthetic-Validation",
"MIDI-B-Synthetic-Test",
"MIDI-B-Curated-Test",
"ReMIND",
"Mouse-Astrocytoma",
"TCGA-SARC",
"QIBA CT-1C",
"Pseudo-PHI-DICOM-Data",
"Vestibular-Schwannoma-MC-RC",
"Vestibular-Schwannoma-SEG",
"TCGA-THCA",
"TCGA-CESC",
"CPTAC-CCRCC",
"CC-Tumor-Heterogeneity",
"ICDC-Glioma",
"PDMR-997537-175-T",
"CT COLONOGRAPHY",
"QIBA-CT-Liver-Phantom",
"MRI-DIR",
"PDMR-521955-158-R4",
"VAREPOP-APOLLO",
"CPTAC-AML",
"Prostate Fused-MRI-Pathology",
"Phantom FDA",
"NSCLC-Radiomics-Interobserver1",
"EA1141",
"Prostate-3T",
"Pediatric-CT-SEG",
"LCTSC",
"DRO-Toolkit",
"CMMD",
"ACRIN-6698",
"Pancreas-CT",
"CPTAC-CM",
"CMB-OV",
"Advanced-MRI-Breast-Lesions",
"CMB-GEC",
"PDMR-292921-168-R",
"CPTAC-SAR",
"BREAST-DIAGNOSIS",
"ISPY1",
"CPTAC-LSCC",
"TCGA-BLCA",
"CPTAC-UCEC",
"Breast-Cancer-Screening-DBT",
"TCGA-COAD",
"CMB-MEL",
"CT Lymph Nodes"
]