name: CI-CD

# run on any push to any directory and a pull to main or development
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ################################################################################################
  # Docs: Build and deploy mkdocs documentation
  ################################################################################################
  Docs:
    runs-on: ubuntu-latest

    permissions:
      # Need to give the action permission to write to the repository to deploy the docs
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.42.1
          environments: docs
          cache: true
          locked: false

      - name: Build documentation
        run: pixi run -e docs build

      - name: Build and deploy documentation (only on push to main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: pixi run -e docs mike deploy --push dev devel

  ################################################################################################
  Tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        env: ["py310", "py311", "py312"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          environments: ${{ matrix.env }}
          pixi-version: v0.41.3
          cache: true
          locked: false
      - name: Run tests
        run: |
          pixi run -e ${{ matrix.env }} test

  ################################################################################################
  # CD: Continuous Deployment
  ################################################################################################
  release-please:
    runs-on: ubuntu-latest
    needs: [Docs, Tests]
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.SEMVER_APP_KEY }}

  # --------------------------------------
  # Publish to PyPI when a release is tagged
  # --------------------------------------
  Publish-To-PyPi:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      PIXI_ENV: publish

    steps:
      - name: Checkout the tagged release
        uses: actions/checkout@v5

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          environments: ${{ env.PIXI_ENV }}
          pixi-version: v0.41.3
          cache: true
          locked: false

      - name: Publish to PyPI
        env:
          HATCH_INDEX_USER: ${{ secrets.PYPI_USERNAME }}
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
          HATCH_INDEX_REPO: https://upload.pypi.org/legacy/
        run: |
          pixi run publish-pypi